In [ ]:
from sqlalchemy import create_engine # noqa
import pandas as pd
import json

# crée un moteur SQLAlchemy pour MySQL
engine = create_engine("mysql+pymysql://user:password@localhost/mydatabase")


conn = engine.connect()

query = """
SELECT *
FROM ecommerce;
"""

df = pd.read_sql(query, conn)   
conn.close()
display(df.head())


# export json
data = df.to_dict(orient='records')
with open('ecommerce.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=4)
    
# lire le fichier json
with open('ecommerce.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
display(data[:2])  # afficher les deux premiers enregistrements

   customerID  full_name purchase_date total_spent newsletter_optin
0          13  Client_11    08-10-2023     436.86€              Yes
1          10   Client_8    24-02-2023     238.32€
2          18  Client_18    12-01-2023      92.62€
3          21   Client_9    07-01-2023     394.42€               No
4           9  Client_17    22-03-2023     184.17€              Yes